### ISSUE TITLE
Warnings config import / export 

### ISSUE THREAD

**Issue by 4O4** [dotboris/prod-guard#468]
Hi, great extension! Would it be possible to add ability to import and export config so that it can be easily shared between people? A simple textarea with JSON dump and two buttons would be enough I guess :)

**Comment by dotboris** [comment]
Hi there,

Thank you for the suggestion. It sounds like a great idea.

This feature seems pretty feasible to me. A simple UI like you described should do the job. One thing that is missing internally for such a feature to work well is globally unique IDs for warnings. This would allow the extension to know whether or not it needs to create a new warning or update an existing one when importing.

I'm currently pretty busy and I don't have time to work on this. If you or someone else wants to contribute, feel free to do so. Once I find some free time I'll check in on this and start implementing it if need be.

**Comment by dotboris** [comment]
:wave: @4O4. I just wanted to let you know that as of [v1.4.0](https://github.com/dotboris/prod-guard/releases/tag/v1.4.0), Prod Guard is able to export / import its data. This is available through the new Settings menu:

![image](https://github.com/dotboris/prod-guard/assets/1874242/be7cb932-2af5-4b06-84e2-0e7c340ac0b8)
