### ISSUE TITLE
Add option for side banner

### ISSUE THREAD

**Issue by invisibleninja06** [dotboris/prod-guard#527]
When dealing with bootstrap style pages the top and bottom banner options often cover up the nav or footer bars.
The border option works but is not as in your face as the banner style

What would be nice is the option to have a floating side banner that vertically prints the warning message.

**Comment by dotboris** [comment]
I have implemented an alternate solution for you in https://github.com/dotboris/prod-guard/pull/754. With this change, the top & bottom banners will automatically hide when the mouse is close and you will be able to click & interact with the element that would be underneath the banner.

I'm going to release this soon and I'll let you know when it's out.
