### ISSUE TITLE
Banner stays invisible when already invisible and cursors gets out of the window

### ISSUE THREAD

**Issue by binaryannie** [dotboris/prod-guard#774]
## To reproduce

1. Setup a top banner
2. Mouse over the banner to get it to disappear
3. Go out of the window
4. The banner stay invisible

## Expected behaviour

The banner should re-appear when cursor gets out of the window.

## Banner setup

![image](https://user-images.githubusercontent.com/3219012/159922745-269d27c6-ec2b-4be8-ba31-389d6eea47f2.png)

## Recording

https://user-images.githubusercontent.com/3219012/159923181-68e7bb53-64f6-4873-9863-d32cce0ce4ff.mov

**Comment by dotboris** [comment]
I've released a fix for this in v1.3.1 which I've published to both the Chrome web store as well as the Mozilla addon's site.

The firefox add-on has already been approved and is available to use. The Chrome version is still waiting for a review. Those don't usually take that long to complete, I'm guessing that it should be out at the start of the week.

**Comment by dotboris** [comment]
I just checked and v1.3.1 has been published for chrome as well :tada:

**Comment by binaryannie** [comment]
So efficient, thanks a lot 🙏 ❤️
